
exports.seed = function(knex, Promise) {
  // Deletes ALL existing entries
  return knex('games').del()
    .then(function () {
      return Promise.all([
        // Inserts seed entries
        knex('games').insert({
           course_id: '1',
           date: '11/18/16',
           score1: 5,
           score2: 4,
           score3: 4,
           score4: 4,
           score5: 3,
           score6: 4,
           score7: 4,
           score8: 6,
           score9: 3,
           score10: 4,
           score11: 5,
           score12: 4,
           score13: 5,
           score14: 3,
           score15: 4,
           score16: 3,
           score17: 4,
           score18: 4,
           handicap: 1,
        }),
        knex('games').insert({
           course_id: '3',
           date: '11/21/16',
           score1: 5,
           score2: 5,
           score3: 3,
           score4: 4,
           score5: 4,
           score6: 3,
           score7: 3,
           score8: 4,
           score9: 5,
           score10: 7,
           score11: 3,
           score12: 6,
           score13: 3,
           score14: 4,
           score15: 4,
           score16: 4,
           score17: 4,
           score18: 4,
           handicap: 3,
        }),
        knex('games').insert({
           course_id: '5',
           date: '11/26/16',
           score1: 4,
           score2: 4,
           score3: 5,
           score4: 4,
           score5: 6,
           score6: 6,
           score7: 5,
           score8: 4,
           score9: 4,
           score10: 5,
           score11: 4,
           score12: 3,
           score13: 3,
           score14: 4,
           score15: 5,
           score16: 4,
           score17: 4,
           score18: 4,
           handicap: 6,
        }),
        knex('games').insert({
           course_id: '8',
           date: '12/01/16',
           score1: 5,
           score2: 5,
           score3: 5,
           score4: 4,
           score5: 6,
           score6: 6,
           score7: 5,
           score8: 4,
           score9: 4,
           score10: 5,
           score11: 4,
           score12: 3,
           score13: 3,
           score14: 4,
           score15: 5,
           score16: 4,
           score17: 4,
           score18: 4,
           handicap: 8,
        }),
      ]);
    });
};
